language: python
sudo: false
addons:
  apt_packages:
    - pandoc
python:
- '2.7'
install:
  - pip install -U pip wheel
  - pip install tox-travis
  - pip install setuptools-markdown
script: tox
deploy:
  provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: $pypi_user
  password: $pypi_password    
  on:
    tags: true
    repo: jcooklin/snap-plugin-lib-py
    condition: $TRAVIS_PYTHON_VERSION = "2.7"