language: python
sudo: false
addons:
  apt_packages:
    - pandoc
python:
- '3.5'
install:
  - pip install -U pip wheel
  - pip install tox-travis
  - pip install setuptools-markdown  
script: tox
deploy:
  provider: pypi
  distributions: bdist_wheel
  server: https://testpypi.python.org/pypi
  user: $pypi_user
  password: $pypi_password    
  on:
    all_branches: true    
    repo: jcooklin/snap-plugin-lib-py    